// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtsaq7uhreicseUtvzzPyF7i0speMvoo0',
    appId: '1:2614100063:web:3a20a642d157ef78755bea',
    messagingSenderId: '2614100063',
    projectId: 'flutter-tasks-app-a5fa0',
    authDomain: 'flutter-tasks-app-a5fa0.firebaseapp.com',
    storageBucket: 'flutter-tasks-app-a5fa0.firebasestorage.app',
    measurementId: 'G-L19Y62L85W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25nrSBl0JNVmQeop_aywo4SSe5bdnxxQ',
    appId: '1:2614100063:android:9db038929235fa63755bea',
    messagingSenderId: '2614100063',
    projectId: 'flutter-tasks-app-a5fa0',
    storageBucket: 'flutter-tasks-app-a5fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEopJ8CGs-ACHWa65aKpSV_Wb-Upz0Q7c',
    appId: '1:2614100063:ios:4289bcd33af0baaa755bea',
    messagingSenderId: '2614100063',
    projectId: 'flutter-tasks-app-a5fa0',
    storageBucket: 'flutter-tasks-app-a5fa0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTasksApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEopJ8CGs-ACHWa65aKpSV_Wb-Upz0Q7c',
    appId: '1:2614100063:ios:4289bcd33af0baaa755bea',
    messagingSenderId: '2614100063',
    projectId: 'flutter-tasks-app-a5fa0',
    storageBucket: 'flutter-tasks-app-a5fa0.firebasestorage.app',
    iosBundleId: 'com.example.flutterTasksApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtsaq7uhreicseUtvzzPyF7i0speMvoo0',
    appId: '1:2614100063:web:a1ed8a657b3cb363755bea',
    messagingSenderId: '2614100063',
    projectId: 'flutter-tasks-app-a5fa0',
    authDomain: 'flutter-tasks-app-a5fa0.firebaseapp.com',
    storageBucket: 'flutter-tasks-app-a5fa0.firebasestorage.app',
    measurementId: 'G-SC3Q4X3LCG',
  );
}
